// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prenumerantsystem.Data;

#nullable disable

namespace Prenumerantsystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515130310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prenumerantsystem.Models.Prenumerant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fornamn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Postnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Prenumerationsnummer")
                        .HasColumnType("integer");

                    b.Property<string>("Utdelningsadress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Prenumeranter");
                });
#pragma warning restore 612, 618
        }
    }
}
